version: '3.7'

services:

  tracer_v1:
    image: registry.ddbuild.io/apm-integrations-testing/handmade/go-gin:1.14.tracer_v1
    build:
      context: .
      args:
        - branch=datadog-trace
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - DD_AGENT_HOST=agent
      - DD_GO_HASH=${DD_GO_HASH}
    depends_on:
      - agent

  notracer:
    image: registry.ddbuild.io/apm-integrations-testing/handmade/go-gin:1.14.notracer
    build:
      context: .
      args:
        - branch=datadog-notrace
    ports:
      - 0.0.0.0:8081:8080
    environment:
      - DD_AGENT_HOST=agent
    depends_on:
      - agent

  agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_ENV=testenv
